#!/usr/bin/env node
import fs from "node:fs";

function parseArgs(argv) {
  const options = {
    appcast: "appcast.xml",
  };

  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    if (!arg.startsWith("--")) {
      throw new Error(`Unexpected argument: ${arg}`);
    }

    const key = arg.slice(2);
    const value = argv[index + 1];
    if (!value || value.startsWith("--")) {
      throw new Error(`Missing value for ${arg}`);
    }

    options[key] = value;
    index += 1;
  }

  return options;
}

function required(options, key) {
  const value = options[key];
  if (!value) {
    throw new Error(`Missing required option --${key}.`);
  }
  return value;
}

function escapeXml(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

function formatPubDate(date) {
  const weekdays = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
  const months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
  const pad = (value) => String(value).padStart(2, "0");

  return `${weekdays[date.getUTCDay()]}, ${pad(date.getUTCDate())} ${months[date.getUTCMonth()]} ${date.getUTCFullYear()} ${pad(date.getUTCHours())}:${pad(date.getUTCMinutes())}:${pad(date.getUTCSeconds())} +0000`;
}

function maxExistingBuild(appcast) {
  const builds = [...appcast.matchAll(/<sparkle:version>([0-9]+)<\/sparkle:version>/g)]
    .map((match) => Number.parseInt(match[1], 10))
    .filter(Number.isFinite);

  return builds.length ? Math.max(...builds) : 0;
}

function buildItem({
  tag,
  version,
  build,
  signature,
  length,
  pubDate,
  releaseNotesUrl,
  assetUrl,
}) {
  return [
    `        <!-- ${escapeXml(version)} (build ${escapeXml(build)}). Generated by GitHub Actions release workflow. -->`,
    "        <item>",
    `            <title>Version ${escapeXml(version)}</title>`,
    `            <link>https://github.com/jsgrrchg/MoodistMac/releases/tag/${escapeXml(tag)}</link>`,
    `            <sparkle:version>${escapeXml(build)}</sparkle:version>`,
    `            <sparkle:shortVersionString>${escapeXml(version)}</sparkle:shortVersionString>`,
    `            <sparkle:releaseNotesLink>${escapeXml(releaseNotesUrl)}</sparkle:releaseNotesLink>`,
    `            <sparkle:fullReleaseNotesLink>${escapeXml(releaseNotesUrl)}</sparkle:fullReleaseNotesLink>`,
    `            <pubDate>${escapeXml(pubDate)}</pubDate>`,
    "            <enclosure",
    `                url="${escapeXml(assetUrl)}"`,
    `                sparkle:edSignature="${escapeXml(signature)}"`,
    `                length="${escapeXml(length)}"`,
    '                type="application/octet-stream"/>',
    "        </item>",
  ].join("\n");
}

const options = parseArgs(process.argv.slice(2));
const appcastPath = options.appcast;
const tag = required(options, "tag");
const version = required(options, "version");
const build = required(options, "build");
const signature = required(options, "signature");
const length = required(options, "length");
const releaseNotesUrl = required(options, "release-notes-url");
const assetUrl = required(options, "asset-url");
const pubDate = options["pub-date"] ?? formatPubDate(new Date());

if (!/^v[0-9]+\.[0-9]+\.[0-9]+$/.test(tag)) {
  throw new Error(`Release tag must use vX.Y.Z format: ${tag}`);
}

if (tag !== `v${version}`) {
  throw new Error(`Tag ${tag} does not match version ${version}.`);
}

if (!/^[0-9]+$/.test(build) || Number.parseInt(build, 10) < 1) {
  throw new Error(`Build must be a positive integer: ${build}`);
}

if (!/^[0-9]+$/.test(length) || Number.parseInt(length, 10) < 1) {
  throw new Error(`Length must be a positive integer: ${length}`);
}

const appcast = fs.readFileSync(appcastPath, "utf8");

if (appcast.includes(`<sparkle:shortVersionString>${version}</sparkle:shortVersionString>`)) {
  throw new Error(`appcast already contains version ${version}.`);
}

const highestBuild = maxExistingBuild(appcast);
if (Number.parseInt(build, 10) <= highestBuild) {
  throw new Error(`Build ${build} must be greater than highest appcast build ${highestBuild}.`);
}

const insertionAnchor =
  appcast.match(/^[ \t]*<language>[^<]*<\/language>\r?\n/m) ??
  appcast.match(/^[ \t]*<description>[^<]*<\/description>\r?\n/m);
if (insertionAnchor?.index === undefined) {
  throw new Error("Could not find appcast metadata insertion point.");
}
const insertionIndex = insertionAnchor.index + insertionAnchor[0].length;

const item = buildItem({
  tag,
  version,
  build,
  signature,
  length,
  pubDate,
  releaseNotesUrl,
  assetUrl,
});

const updated = `${appcast.slice(0, insertionIndex)}${item}\n${appcast.slice(insertionIndex)}`;
fs.writeFileSync(appcastPath, updated);

console.log(`Inserted appcast item for ${tag}.`);
